apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: auth-mongo-pvc
spec:
    storageClassName: hostpath
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    selector:
        matchLabels:
            name: auth-mongo-pv
