apiVersion: v1
kind: PersistentVolume
metadata:
    name: auth-mongo-pv
    labels:
        name: auth-mongo-pv
        type: standard
spec:
    storageClassName: hostpath
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mnt/data"
