apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: em-mongo-pvc
spec:
    storageClassName: hostpath
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    selector:
        matchLabels:
            name: em-mongo-pv
